account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .forms import (PwdResetConfirmForm, PwdResetForm, UserLoginForm)

# https://docs.djangoproject.com/en/3.1/topics/auth/default/
# https://ccbv.co.uk/projects/Django/3.0/django.contrib.auth.views/PasswordResetConfirmView/

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html',
                                                form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name='logout'),
    path('register/', views.account_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>)/', views.account_activate, name='activate'),
    # Reset password
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="account/password_reset/password_reset_form.html",
                                                                 success_url='password_reset_email_confirm',
                                                                 email_template_name='account/password_reset/password_reset_email.html',
                                                                 form_class=PwdResetForm), name='pwdreset'),
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset/password_reset_confirm.html',
                                                                                                success_url='password_reset_complete/',
                                                                                                form_class=PwdResetConfirmForm),
         name="password_reset_confirm"),
    path('password_reset/password_reset_email_confirm/',
         TemplateView.as_view(template_name="account/password_reset/reset_status.html"), name='password_reset_done'),
    path('password_reset_confirm/Mg/password_reset_complete/',
         TemplateView.as_view(template_name="account/password_reset/reset_status.html"), name='password_reset_complete'),
    # User dashboard
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/edit/', views.edit_details, name='edit_details'),
    path('profile/delete_user/', views.delete_user, name='delete_user'),
    path('profile/delete_confirm/', TemplateView.as_view(template_name="account/dashboard/delete_confirm.html"), name='delete_confirmation'),
]

basket/urls.py
from django.urls import path

from . import views

from basket.transbankpay import webpay_plus_create, commitpay

app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),
    path('webpay-plus-create', webpay_plus_create, name='webpay-plus-create'),
    path('commit-pay/', commitpay),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('account/', include('account.urls', namespace='account')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('generic/', include('generic.urls', namespace='generic')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.product_all, name='store_home'),
    path('<slug:slug>', views.product_detail, name='product_detail'),
    path('shop/<slug:category_slug>/', views.category_list, name='category_list'),
]

store/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.core.validators import MaxValueValidator


class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)


class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('store:category_list', args=[self.slug])

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='product_creator')
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, default='admin')
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/', default='images/default.png')
    slug = models.SlugField(max_length=255)
    price = models.PositiveIntegerField(validators=[MaxValueValidator(999999)])
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    products = ProductManager()

    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug])

    def __str__(self):
        return self.title

store/views.py
from django.shortcuts import get_object_or_404, render

from .models import Category, Product


def product_all(request):
    products = Product.products.all()
    return render(request, 'store/index.html', {'products': products})


def category_list(request, category_slug=None):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.products.filter(category=category)
    return render(request, 'store/category.html', {'category': category, 'products': products})


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, in_stock=True)
    return render(request, 'store/single.html', {'product': product})
    

templates/store/category.html
{% extends "../base.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Productos{% endif %}
{% endblock %}
{% block content %}

<div class="container" style="max-width: 1000px">
  <div class="col-12">
    <h1 class="h2">{{ category.name|title }}</h1>
  </div>
  <div class="col-12 d-flex justify-content-between">
    <div>Productos <b>Más Vendidos</b></div>
  </div>
  <hr />
</div>
<div class="container">
  <div class="row">
    <div class="album">
      {% if not products %}
      <div class="col-12">Actualmente no hay productos activos <a href="{% url 'store:store_home' %}">Home</a></div>
      {% else %}
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
        {% for product in products%}
                                  <div class="col-sm-6 col-lg-4">
                                      <div class="product mb-0">
                                          <div class="product-thumb-info border-0 mb-3">

                                              <div class="product-thumb-info-badges-wrapper">
                                                  <span class="badge badge-ecommerce badge-success">NEW</span>

                                              </div>

                                              <div class="addtocart-btn-wrapper" >
                                                  <a href="" class="text-decoration-none addtocart-btn" title="Añadir al Carrito">
                                                      <i class="icons icon-bag"></i>
                                                </a>
                                              </div>
                                              <a href="{{ product.get_absolute_url }}">
                                                  <div class="product-thumb-info-image">
                                                      {%if product.image%}
                                                          <img class="" src="{{ product.image.url }}" height="150" weight="250" alt="">
                                                      {%endif%}

                                                  </div>
                                              </a>
                                          </div>
                                          <div class="d-flex justify-content-between">
                                              <div>
                                                  <a href="#" class="d-block text-uppercase text-decoration-none text-color-default text-color-hover-primary line-height-1 text-0 mb-1">{{product.category}}</a>
                                                  <h3 class="text-3-5 font-weight-medium font-alternative text-transform-none line-height-3 mb-0"><a href="{{ product.get_absolute_url }}" class="text-color-dark text-color-hover-primary">{{product.title}}</a></h3>
                                              </div>
                                              <a href="#" class="text-decoration-none text-color-default text-color-hover-dark text-4"><i class="far fa-heart"></i></a>
                                          </div>
                                          <div title="Rated 5 out of 5">
                                              <input type="text" class="d-none" value="5" title="" data-plugin-star-rating data-plugin-options="{'displayOnly': true, 'color': 'default', 'size':'xs'}">
                                          </div>
                                          <p class="price text-5 mb-3">
                                              <span class="sale text-color-dark font-weight-semi-bold">${{product.price|floatformat:0}}</span>
                                              <!--<span class="amount">100.00</span>-->
                                          </p>
                                      </div>
                                  </div>
                                  {%endfor%}
      </div>
      {% endif %}
    </div>
  </div>
</div>

{% endblock %}

templates/store/index.html
{% extends "base.html" %}
{% block title %}Óptica - Mejora tu vista!{% endblock %}
{% block content %}
<div role="main" class="main shop pt-4">
  {% comment %} ACÁ SE INSERTA LA IMAGEN DE FONDO {% endcomment %}
  <section class="page-header page-header-modern section position-relative border-0 m-0 " style="background-image: url(static/core/images/kk.webp); background-position: center; background-size: cover;">
    <div class="container position-relative pb-5 mb-5">
      
      <div class="row text-center text-md-start py-2">
        <div class="col p-relative bottom-5">
          <ul class="breadcrumb d-block text-4 opacity-8 text-default mb-0">
            <li><a href="/" class="text-decoration-none text-default">Home</a></li>
            <li class="active">Nuestra Tienda</li>
          </ul>
          
          <h1 class="font-weight-bold text-color-white text-10 mt-1 mb-0">Potencia tus ventas al menos un 200%</h1>
          <br>
          <h1 class="font-weight-bold text-color-white text-10 mt-1 mb-0">Con una pagina web potente</h1>
        </div>
      </div>
    </div>
  </section>
  

      <div class="container">       

        <div class="my-5 py-5">
          <h1 class="h1">Precios de suscripciones</h1>
        </div>

          <div class="row">
              <div class="col-lg-12">
                  <div class="masonry-loader masonry-loader-showing">
                      <div class="row products product-thumb-info-list" data-plugin-masonry data-plugin-options="{'layoutMode': 'fitRows'}">

                                  {% for product in products%}
                                  <div class="col-sm-6 col-lg-4">
                                      <div class="product mb-0">
                                          <div class="product-thumb-info border-0 mb-3">

                                              <div class="product-thumb-info-badges-wrapper">
                                                  <span class="badge badge-ecommerce badge-success">NEW</span>

                                              </div>

                                              <div class="addtocart-btn-wrapper" >
                                                  <a href="" class="text-decoration-none addtocart-btn" title="Añadir al Carrito">
                                                      <i class="icons icon-bag"></i>
                                                </a>
                                              </div>

                                              <a href="{{ product.get_absolute_url }}" class="quick-view text-uppercase font-weight-semibold text-2">
                                                  VER
                                              </a>
                                              <a href="{{ product.get_absolute_url }}">
                                                  <div class="product-thumb-info-image">
                                                      {%if product.image%}
                                                          <img class="" src="{{ product.image.url }}" height="150" weight="250" alt="">
                                                      {%endif%}

                                                  </div>
                                              </a>
                                          </div>
                                          <div class="d-flex justify-content-between">
                                              <div>
                                                  <a href="#" class="d-block text-uppercase text-decoration-none text-color-default text-color-hover-primary line-height-1 text-0 mb-1">{{product.category}}</a>
                                                  <h3 class="text-3-5 font-weight-medium font-alternative text-transform-none line-height-3 mb-0"><a href="{{ product.get_absolute_url }}" class="text-color-dark text-color-hover-primary">{{product.title}}</a></h3>
                                              </div>
                                              <a href="#" class="text-decoration-none text-color-default text-color-hover-dark text-4"><i class="far fa-heart"></i></a>
                                          </div>
                                          <div title="Rated 5 out of 5">
                                              <input type="text" class="d-none" value="5" title="" data-plugin-star-rating data-plugin-options="{'displayOnly': true, 'color': 'default', 'size':'xs'}">
                                          </div>
                                          <p class="price text-5 mb-3">
                                              <span class="sale text-color-dark font-weight-semi-bold">${{product.price|floatformat:0}}</span>
                                              <!--<span class="amount">100.00</span>-->
                                          </p>
                                      </div>
                                  </div>
                                  {%endfor%}
                      </div>
                  </div>
              </div>
          </div>
      </div>

      {% comment %} ACÁ SE INSERTA LA OTRA IMAGEN DE FONDO {% endcomment %}
      <section class="page-header page-header-modern section position-relative border-0 mt-5" style="background-image: url(static/core/images/top.jpg); background-position: center; background-size: cover;">
        <div class="container position-relative pb-5 mb-5">
    
          <div class="row text-center text-md-start py-2">
            <div class="col p-relative bottom-5">
              <a href="{% url "account:register" %}"><h1 class="font-weight-bold text-color-dark text-7 mt-5 mb-0">Regístrate Aquí y Recibe todas nuestras Ofertas</h1></a>
            </div>
          </div>
        </div>
      </section>
      <div>
        <section class="contenedor sobre-nosotros">
              <h2 class="titulo">Nuestro servicio</h2>
              <div class="contenedor-sobre-nosotros">
                <img src="static/core/images/woman-glasses.jpg" alt="" class="imagen-about-us">
                <div class="contenido-texto">
                    <h3><span>1</span>los mejores servicios</h3>
                    <p>Implementamos soluciones de Comercio Electrónico en dos sabores diferentes
                      Conocemos las problemáticas más comunes que enfrentan las
                       empresas de diferentes tamaños al momento de implementar soluciones de 
                       comercio electrónico, y asesoramos para llevar a cabo los procesos online
                       y offline asociados a estas actividades.
                      
                      Entregamos servicios de Diseño, Ingeniería, y Marketing, para realizar 
                      proyectos donde Internet es el canal de comunicación. Complementamos 
                      nuestros esfuerzos con productos (herramientas de software) desarrollados,
                      para entregar soluciones rápidas y personalizadas.
                      
                      Hemos desarrollado un grupo de Herramientas orientadas a satisfacer 
                      Diversas Necesidades dentro de las Empresas, todas en Ambiente Web, 
                      sobre plataformas de Código Abierto. Complementamos nuestros Productos 
                      con servicios de Diseño e Ingeniería, para Personalizarlos e Integrarlos 
                      a sistemas o procesos externos.</p>
                                     
                </div>
              </div> 
        </section>
        <section class="portafolio">
          <div class="contenedor">
            <h2 class="titulo">Portafolio</h2>
            <div class="galeria-port">
              <div class="imagen-port">
                <img src="static/core/images/imagenSolux.jpg" alt="">
                <div class="hover-galeria">
                  <img src="static/core/images/R.jpg" alt="">
                  <p>Nuestro trabajo</p>
                </div>
                                                   
              </div>
              <div class="imagen-port">
                <img src="static/core/images/inscripcion.jpg" alt="">
                <div class="hover-galeria">
                  <img src="static/core/images/R.jpg" alt="">
                  <p>Nuestro trabajo</p>
                </div>
                                                   
              </div>
              <div class="imagen-port">
                <img src="static/core/images/proveedor.png" alt="">
                <div class="hover-galeria">
                  <img src="static/core/images/R.jpg" alt="">
                  <p>Nuestro trabajo</p>
                </div>
                                                   
              </div>
              <div class="imagen-port">
                <img src="static/core/images/quien.jpg" alt="">
                <div class="hover-galeria">
                  <img src="static/core/images/R.jpg" alt="">
                  <p>Nuestro trabajo</p>
                </div>
                                                   
              </div>
              <div class="imagen-port">
                <img src="static/core/images/RR.webp" alt="">
                <div class="hover-galeria">
                  <img src="static/core/images/R.jpg" alt="">
                  <p>Nuestro trabajo</p>
                </div>
                                                   
              </div>
              <div class="imagen-port">
                <img src="static/core/images/S.jpg" alt="">
                <div class="hover-galeria">
                  <img src="static/core/images/R.jpg" alt="">
                  <p>Nuestro trabajo</p>
                </div>
                                                   
              </div>
              <div class="imagen-port">
                <img src="static/core/images/top.jpg" alt="">
                <div class="hover-galeria">
                  <img src="static/core/images/R.jpg" alt="">
                  <p>Nuestro trabajo</p>
                </div>
                                                   
              </div>
              <div class="imagen-port">
                <img src="static/core/images/vitrina.jpg" alt="">
                <div class="hover-galeria">
                  <img src="static/core/images/R.jpg" alt="">
                  <p>Nuestro trabajo</p>
                </div>
                                                   
              </div>
              
              
              
            </div>
            </div>
          </div>
        </section>
        
        <section class="clientes contenedor">
          <h2 class="titulo">Que dicen nuestros clientes</h2>
          <div class="cards">
            <div class="card">
                <img src="static/core/images/hombre.png" alt="">
                <div class="contenido-texto-card">
                  <h4>Alejandro Yañez</h4>
                  <p>la experiencia fue excelente con el equipo, desde el primer
                    dia entregaron apoyo, entregaban sugerencias y respondian todas las dudas 
                    que se generaban en el avance.</p>

              </div>
                
              </div>
            </div>

        </section>
              <section class="clientes contenedor">
                <h2 class="titulo">Que dicen nuestros clientes</h2>
                <div class="cards">
                    <div class="card">
                          <img src="static/core/images/mujer.jfif" alt="">
                          <div class="contenido-texto-card">
                            <h4>Carla Sepulveda</h4>
                            <p>Excelente empresa, muy profesionales y siempre dispuestos a 
                              comunicarse para aclara dudas, prestar consejos y atender a las necesidades 
                              del cliente.</p>
            
                          </div>
                      
                    </div>         
                  </div>
            </section>
            <section class="page-header page-header-modern section position-relative border-0 m-0 " style="background-image: url(static/core/images/saas.jpg); background-position: center; background-size: cover;">
              <div class="container position-relative pb-5 mb-5">
                
                <div class="row text-center text-md-start py-2">
                  <div class="col p-relative bottom-5">
                                       
                    
                  </div>
                </div>
              </div>
            </section>
      </div>
</div>

<script>
  $(document).on('click', '#add-button', function (e) {
    e.preventDefault();
    $.ajax({
      type: 'POST',
      url: '{% url "basket:basket_add" %}',
      data: {
        productid: $('#add-button').val(),
        productqty: $('#select option:selected').text(),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: 'post'
      },
      success: function (json) {
        document.getElementById("basket-qty").innerHTML = json.qty
      },
      error: function (xhr, errmsg, err) {}
    });
  })
</script>

  {% endblock %}

templates/store/single.html
{% extends "../base.html" %}
{% load static %} 
{% block stylesheet %}{% static 'store/css/store.css' %}{% endblock %}
{% block title %}
{% if product %}{{ product.title }}{% else %}Producto{% endif %}
{% endblock %}
{% block content %}

<!---->
<div class="body">
<div role="main" class="main shop pt-4">

  <div class="container">

    <div class="row">
      <div class="col">
        <ul class="breadcrumb breadcrumb-style-2 d-block text-4 mb-4">
          <li><a href="{% url "store:store_home" %}" class="text-color-default text-color-hover-primary text-decoration-none">Inicio</a></li>
          <li><a href="{% url "store:store_home" %}" class="text-color-default text-color-hover-primary text-decoration-none">Tienda</a></li>
        </ul>
      </div>
    </div>
    <div class="row">
      <div class="col-md-5 mb-5 mb-md-0">

        <div class="thumb-gallery-wrapper">
          <div class="mb-3">
            <div>
              <img alt="Vista Previa Producto" class="img-fluid" src="{{ product.image.url }}" data-zoom-image="{{ product.image.url }}">
            </div>
          </div>
        </div>

      </div>

      <div class="col-md-7">

        <div class="summary entry-summary position-relative">

          <h1 class="mb-0 font-weight-bold text-7">{{ product.title }}</h1>

          <div class="pb-0 clearfix d-flex align-items-center">
            <div class="review-num">
              <a href="#description" class="text-decoration-none text-color-default text-color-hover-primary" data-hash data-hash-offset="0" data-hash-offset-lg="75" data-hash-trigger-click=".nav-link-reviews" data-hash-trigger-click-delay="1000">
                <span class="count text-color-inherit" itemprop="ratingCount">(2</span> comentarios)
              </a>
            </div>
          </div>

          <div class="divider divider-small">
            <hr class="bg-color-grey-scale-4">
          </div>

          <p class="price mb-3">
            <span class="sale text-color-dark">${{ product.price|floatformat:0}}</span>
          </p>

          <ul class="list list-unstyled text-2">
            <li class="mb-0">Stock: <strong class="text-color-dark">Disponible</strong></li>
            <li class="mb-0">SKU: <strong class="text-color-dark">1234567890</strong></li>
          </ul>

        </div>

        <div class="col-md-5 ps-3 col-lg-5 order-md-last p-0 order-1">
          <div class="d-grid gap-2">
            <div class="d-flex d-flex-inline justify-content-between">
              <div>
                <label for="select">Cantidad </label>
                <select id="select" class="h6 store-select-dropdown">
                  <option value="1">1</option>
                </select>
              </div>
            </div>
            <hr>
            <button type="button" id="add-button" value="{{product.id}}" class="btn btn-success fw500">
              Agregar al Carrito</button>
            <button type="button" id="add-button" value="{{product.id}}" class="btn btn-light fw500">Agregar a
              Favoritos</button>
          </div>
        </div>
</div>
</div>
<!---->

<script>
  $(document).on('click', '#add-button', function (e) {
    e.preventDefault();
    $.ajax({
      type: 'POST',
      url: '{% url "basket:basket_add" %}',
      data: {
        productid: $('#add-button').val(),
        productqty: $('#select option:selected').text(),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: 'post'
      },
      success: function (json) {
        document.getElementById("basket-qty").innerHTML = json.qty
      },
      error: function (xhr, errmsg, err) {}
    });
  })
</script>

{% endblock %}