account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .forms import (PwdResetConfirmForm, PwdResetForm, UserLoginForm)

# https://docs.djangoproject.com/en/3.1/topics/auth/default/
# https://ccbv.co.uk/projects/Django/3.0/django.contrib.auth.views/PasswordResetConfirmView/

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html',
                                                form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name='logout'),
    path('register/', views.account_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>)/', views.account_activate, name='activate'),
    # Reset password
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="account/password_reset/password_reset_form.html",
                                                                 success_url='password_reset_email_confirm',
                                                                 email_template_name='account/password_reset/password_reset_email.html',
                                                                 form_class=PwdResetForm), name='pwdreset'),
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset/password_reset_confirm.html',
                                                                                                success_url='password_reset_complete/',
                                                                                                form_class=PwdResetConfirmForm),
         name="password_reset_confirm"),
    path('password_reset/password_reset_email_confirm/',
         TemplateView.as_view(template_name="account/password_reset/reset_status.html"), name='password_reset_done'),
    path('password_reset_confirm/Mg/password_reset_complete/',
         TemplateView.as_view(template_name="account/password_reset/reset_status.html"), name='password_reset_complete'),
    # User dashboard
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/edit/', views.edit_details, name='edit_details'),
    path('profile/delete_user/', views.delete_user, name='delete_user'),
    path('profile/delete_confirm/', TemplateView.as_view(template_name="account/dashboard/delete_confirm.html"), name='delete_confirmation'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('account/', include('account.urls', namespace='account')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('generic/', include('generic.urls', namespace='generic')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path


from . import views

app_name = 'payment'

urlpatterns = [
    path('', views.BasketView, name='basket'),
    path('orderplaced/', views.order_placed, name='order_placed'),
    path('error/', views.Error.as_view(), name='error'),
    path('webhook/', views.stripe_webhook),
]

payment/models.py
from django.db import models

# Create your models here.

payment/views.py
import json
import os

import stripe
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.base import TemplateView
from django.conf import settings

from basket.basket import Basket
from orders.views import payment_confirmation


def order_placed(request):
    basket = Basket(request)
    basket.clear()
    return render(request, 'payment/orderplaced.html')


class Error(TemplateView):
    template_name = 'payment/error.html'


@login_required
def BasketView(request):

    basket = Basket(request)
    total = str(basket.get_total_price())
    total = total.replace('.', '')
    total = int(total)

    stripe.api_key = settings.STRIPE_SECRET_KEY
    intent = stripe.PaymentIntent.create(
        amount=total,
        currency='gbp',
        metadata={'userid': request.user.id}
    )

    return render(request, 'payment/payment_form.html', {'client_secret': intent.client_secret, 
                                                            'STRIPE_PUBLISHABLE_KEY': os.environ.get('STRIPE_PUBLISHABLE_KEY')})


@csrf_exempt
def stripe_webhook(request):
    payload = request.body
    event = None

    try:
        event = stripe.Event.construct_from(
            json.loads(payload), stripe.api_key
        )
    except ValueError as e:
        print(e)
        return HttpResponse(status=400)

    # Handle the event
    if event.type == 'payment_intent.succeeded':
        payment_confirmation(event.data.object.client_secret)

    else:
        print('Unhandled event type {}'.format(event.type))

    return HttpResponse(status=200)

templates/payment/error.html
{% extends "./sub_base.html" %}
{% block title %}Error en el Pedido{% endblock %}
{% block content %}

<div class="container">
  <div class="col-12 col-lg-6">
    <h3 class="mb-4">Error en el Pedido</h3>
    <p>Por favor póngase en contacto con nuestro equipo de atención al cliente</p>
    <a href="{% url "account:dashboard" %}">Dashboard</a>
  </div>     
</div>

{% endblock %}

templates/payment/orderplaced.html
{% extends "./sub_base.html" %}
{% block title %}Pedido Realizado{% endblock %}
{% block content %}

<div class="container">
  <div class="col-12 col-lg-6">
    <h3 class="mb-4">Se ha realizado el pedido.</h3>
    <p>Revisa tu correo electrónico para confirmar</p>
    <a href="{% url "account:dashboard" %}">Mis Pedidos</a>
  </div>     
</div>

{% endblock %}

templates/payment/payment_form.html
{% extends "./sub_base.html" %}
{% load static %}
{% block title %}Realizar Pago{% endblock %}

{% block sub_content %}

<form id="payment-form">
  <h3 class="mb-3">Dirección de Envio</h3>
  <!-- Error messages in this element -->
  <div id="card-errors" class="a" role="alert"></div>
  <div class="row g-3">
    <div class="col-sm-7">
      <label for="firstName" class="form-label">Nombre del cliente</label>
      <input type="text" class="form-control" id="custName" placeholder="" required>
      <div class="invalid-feedback">
        Se requiere un nombre válido.
      </div>
    </div>
    <div class="col-12">
      <label for="email" class="form-label">Correo Electrónico <span class="text-muted">(Opcional)</span></label>
      <input type="email" class="form-control" id="email" placeholder="you@example.com">
      <div class="invalid-feedback">
        Ingrese una dirección de correo electrónico válida para actualizaciones de envío.
      </div>
    </div>
    <div class="col-12">
      <label for="address" class="form-label">Dirección</label>
      <input type="text" class="form-control" id="custAdd" placeholder="1234 Main St" required>
      <div class="invalid-feedback">
        Por favor introduzca su direccion de envio.
      </div>
    </div>
    <div class="col-12">
      <label for="address2" class="form-label">Dirección 2 <span class="text-muted">(Opcional)</span></label>
      <input type="text" class="form-control" id="custAdd2" placeholder="Apartment or suite">
    </div>
    <div class="col-md-5">
      <label for="country" class="form-label">País</label>
      <select class="form-select" id="country" required>
        <option value="">Seleccione...</option>
        <option>Chile</option>
      </select>
      <div class="invalid-feedback">
        Seleccione un país válido.
      </div>
    </div>
    <div class="col-md-4">
      <label for="state" class="form-label">Región</label>
      <select class="form-select" id="state" required>
        <option value="">Seleccione...</option>
        <option>Región Metropolitana</option>
      </select>
      <div class="invalid-feedback">
        Proporcione una región válida.
      </div>
    </div>
    <div class="col-md-3">
      <label for="Postcode" class="form-label">Código Postal</label>
      <input type="text" class="form-control" id="postCode" placeholder="" required>
      <div class="invalid-feedback">
        Código postal requerido.
      </div>
    </div>
  </div>
  <hr class="my-4">
  <h4 class="mb-3">Forma de Pago</h4>
  <label for="card-element">Tarjeta de crédito o débito</label>
  <div id="card-element" class="form-control form-control-payment">
    <!-- Payment elements will appear here -->
  </div>
  <hr class="my-4">
  <button id="submit" class="btn btn-primary w-100 fw-bold" data-secret="{{ client_secret }}">Pagar</button>
</form>

<script>
  var STRIPE_PUBLISHABLE_KEY = '{{STRIPE_PUBLISHABLE_KEY}}'
  var CSRF_TOKEN = '{{ csrf_token }}';
</script>
<script src="https://js.stripe.com/v3/"></script>
<script src="{% static 'payment/index.js' %}" data-rel-js></script>

{% endblock %}

templates/payment/sub_base.html
{% extends "../base.html" %}
{% load static %}
{% block stylesheet %}{% static 'payment/css/payment.css' %}{% endblock %}

{% block content %}
<div class="container-fluid">
  <div class="login d-flex align-items-center">
    <div class="col-12 col-md-6  col-lg-6 mx-auto">
      {% block sub_content %}{% endblock %}
    </div>
  </div>
</div>
{% endblock %}